/*
 Navicat Premium Data Transfer

 Source Server         : 115.159.0.240
 Source Server Type    : MySQL
 Source Server Version : 80022
 Source Host           : 115.159.0.240:3306
 Source Schema         : config

 Target Server Type    : MySQL
 Target Server Version : 80022
 File Encoding         : 65001

 Date: 28/02/2021 20:19:24
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 300 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (1, 'payment-library-test.yml', 'SHARED_GROUP', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/test_library?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)', 'cb44a7c8940f6ab377cd99e1578cfde1', '2021-01-03 13:06:21', '2021-01-19 14:11:46', NULL, '58.212.133.156', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (2, 'common-test.yml', 'SHARED_GROUP', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    - classpath*:/mapper/menu/*Mapper.xml\n    - classpath*:/mapper/resource/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.resource.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.organization.notable.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.order.feign: debug\n    com.sh.auth.feign.service: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', 'c4e39ba637a3163301da110b2f925c8b', '2021-01-03 13:11:57', '2021-02-06 07:41:10', NULL, '180.111.133.63', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (5, 'auth', 'PERSISTENCE_GROUP', '  [\n    {\n      \"resource\": \"sentinelTest\",\n      \"limitApp\": \"default\",\n      \"grade\": \"1\",\n      \"count\": \"1\",\n      \"strategy\": \"0\",\n      \"controlBehavior\": \"0\",\n      \"clusterMode\": false\n    }\n  ]', '3d79e98ef4bdf5053951adcdd130cdf4', '2021-01-03 13:18:40', '2021-01-20 17:03:33', NULL, '58.212.133.156', '', 'sentinelPersistence', '', '', '', 'json', '');
INSERT INTO `config_info` VALUES (26, 'account-test.yml', 'TEST_GROUP', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/seata_account?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\nseata:\n  enabled: true\n  application-id: account\n  tx-service-group: my_test_tx_group\n  enable-auto-data-source-proxy: true\n  service:\n    vgroup-mapping:\n      my_test_tx_group: default\n    grouplist:\n      default: seata:8091\n    enable-degrade: false\n    disable-global-transaction: ${seata.service.enable-degrade}\n  config:\n    type: nacos\n    nacos:\n      serverAddr: nacos:8848\n      namespace: seata\n      group: SEATA_GROUP\n  registry:\n    type: ${seata.config.type}\n    nacos:\n      server-addr: ${seata.config.nacos.serverAddr}\n      namespace: ${seata.config.nacos.namespace}\n      application: seata-server    ', '4962821f505e8bbea2341bfa460e15c5', '2021-01-03 14:39:37', '2021-01-20 18:03:49', NULL, '58.212.133.156', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (28, 'order-test.yml', 'TEST_GROUP', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/seata_order?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\nseata:\n  enabled: true\n  application-id: order\n  tx-service-group: my_test_tx_group\n  enable-auto-data-source-proxy: true\n  service:\n    vgroup-mapping:\n      my_test_tx_group: default\n    grouplist:\n      default: seata:8091\n    enable-degrade: false\n    disable-global-transaction: ${seata.service.enable-degrade}\n  config:\n    type: nacos\n    nacos:\n      serverAddr: nacos:8848\n      namespace: seata\n      group: SEATA_GROUP\n  registry:\n    type: ${seata.config.type}\n    nacos:\n      server-addr: ${seata.config.nacos.serverAddr}\n      namespace: ${seata.config.nacos.namespace}\n      application: seata-server\n', '78665b254f4dd38c83ff8b7ce6e83cb0', '2021-01-03 14:40:38', '2021-01-20 18:03:57', NULL, '58.212.133.156', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (48, 'auth-test.yml', 'TEST_GROUP', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8858\n        port: 8719\n      datasource:\n        one:\n          nacos:\n            server-addr: nacos:8848\n            dataId: auth\n            namespace: persistence\n            groupId: PERSISTENCE_GROUP\n            data-type: json\n            rule-type: flow            \n   \n\n', '250e8a7d60301a72d6698d8492b71177', '2021-01-10 15:28:45', '2021-02-07 08:18:16', NULL, '180.111.133.63', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (61, 'organization-test.yml', 'TEST_GROUP', 'spring:\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    dynamic:\n      primary: master\n      strict: false\n      datasource:\n        master:\n          url: jdbc:mysql://mysql:3306/test_library?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n          username: sh\n          password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\n          driver-class-name: com.mysql.cj.jdbc.Driver\n        sqlserver:\n          url: jdbc:sqlserver://10.250.60.63:1433;DatabaseName=im\n          username: sa\n          password: sqlserver2012\n          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver\n  redis:\n    host: redis\n    password: 123456\n\nminio:\n  endpoint: http://minio:9000\n  access-key: minio\n  secret-key: minio123456\n  bucket-name: head   \n\n', '68871bca99c496b026acf0eb0211dc53', '2021-01-15 08:16:15', '2021-02-19 10:56:25', NULL, '49.74.67.42', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (79, 'gateway-test.yml', 'TEST_GROUP', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/oauth/rsa_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/sentinel/test\'\n\n', 'e384e5891637fe3b04d56e20c65514fa', '2021-01-17 22:27:32', '2021-02-28 12:17:37', NULL, '49.74.67.42', '', 'test', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (108, 'msg-test.yml', 'SHARED_GROUP', 'spring:\r\n  rabbitmq:\r\n    host: rabbitmq\r\n    port: 5672\r\n    username: admin\r\n    password: ${spring.rabbitmq.username}\r\n    virtual-host: /\r\n', 'a23bf6cbdf2cac09f10ea1d49eb3b59a', '2021-01-19 14:18:56', '2021-01-19 14:18:56', NULL, '58.212.133.156', '', 'test', NULL, NULL, NULL, 'yaml', NULL);
INSERT INTO `config_info` VALUES (115, 'escription', 'PERSISTENCE_GROUP', '  [\n    {\n      \"resource\": \"oauthToken\",\n      \"limitApp\": \"default\",\n      \"grade\": \"1\",\n      \"count\": \"1\",\n      \"strategy\": \"0\",\n      \"controlBehavior\": \"0\",\n      \"clusterMode\": false\n    }\n  ]\n\n// resource：资源名，即限流规则的作用对象\n// limitApp：流控针对的调用来源，若为 default 则不区分调用来源\n// grade：限流阈值类型（QPS 或并发线程数）\n// count：限流阈值\n// strategy：调用关系限流策略\n// controlBehavior：流量控制效果（直接拒绝、Warm Up、匀速排队）\n// clusterMode：是否集群\n', '4ba5fa7fd268b6e47655ef211a20eee9', '2021-01-20 05:44:45', '2021-01-20 06:19:39', NULL, '58.212.133.156', '', 'sentinelPersistence', '', '', '', 'json', '');
INSERT INTO `config_info` VALUES (138, 'auth', 'PERSISTENCE_GROUP', '  [\r\n    {\r\n      \"resource\": \"sentinelTest\",\r\n      \"limitApp\": \"default\",\r\n      \"grade\": \"1\",\r\n      \"count\": \"1\",\r\n      \"strategy\": \"0\",\r\n      \"controlBehavior\": \"0\",\r\n      \"clusterMode\": false\r\n    }\r\n  ]', '267274dd3cd34f697b92b26b6aaaf490', '2021-01-20 17:08:40', '2021-01-20 17:08:40', NULL, '58.212.133.156', '', 'persistence', NULL, NULL, NULL, 'json', NULL);
INSERT INTO `config_info` VALUES (232, 'service.vgroupMapping.my_test_tx_group', 'SEATA_GROUP', 'default', 'c21f969b5f03d33d43e04f8f136e7682', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (233, 'store.mode', 'SEATA_GROUP', 'db', 'd77d5e503ad1439f585ac494268b351b', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (234, 'store.db.datasource', 'SEATA_GROUP', 'druid', '3d650fb8a5df01600281d48c47c9fa60', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (235, 'store.db.dbType', 'SEATA_GROUP', 'mysql', '81c3b080dad537de7e10e0987a4bf52e', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (236, 'store.db.driverClassName', 'SEATA_GROUP', 'com.mysql.cj.jdbc.Driver', '33763409bb7f4838bde4fae9540433e4', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (237, 'store.db.url', 'SEATA_GROUP', 'jdbc:mysql://115.159.0.240:3306/seata?characterEncoding=utf8', 'e0dde283d31ac342ba9f36701019411b', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (238, 'store.db.user', 'SEATA_GROUP', 'sh', '77cbc257e66302866cf6191754c0c8e3', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (239, 'store.db.password', 'SEATA_GROUP', 'sh20000907', '89f22e4faa82c78ed0d2727318a9da86', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (240, 'store.db.minConn', 'SEATA_GROUP', '5', 'e4da3b7fbbce2345d7772b0674a318d5', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (241, 'store.db.maxConn', 'SEATA_GROUP', '30', '34173cb38f07f89ddbebc2ac9128303f', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (242, 'store.db.globalTable', 'SEATA_GROUP', 'global_table', '8b28fb6bb4c4f984df2709381f8eba2b', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (243, 'store.db.branchTable', 'SEATA_GROUP', 'branch_table', '54bcdac38cf62e103fe115bcf46a660c', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (244, 'store.db.queryLimit', 'SEATA_GROUP', '100', 'f899139df5e1059396431415e770c6dd', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (245, 'store.db.lockTable', 'SEATA_GROUP', 'lock_table', '55e0cae3b6dc6696b768db90098b8f2f', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (246, 'store.db.maxWait', 'SEATA_GROUP', '5000', 'a35fe7f7fe8217b4369a0af4244d1fca', '2021-01-21 07:56:05', '2021-01-21 07:56:05', NULL, '172.18.0.1', '', 'seata', NULL, NULL, NULL, 'text', NULL);
INSERT INTO `config_info` VALUES (247, 'storage-test.yml', 'TEST_GROUP', 'spring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://mysql:3306/seata_storage?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\r\n    username: sh\r\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\r\nseata:\r\n  enabled: true\r\n  application-id: storage\r\n  tx-service-group: my_test_tx_group\r\n  enable-auto-data-source-proxy: true\r\n  service:\r\n    vgroup-mapping:\r\n      my_test_tx_group: default\r\n    grouplist:\r\n      default: seata:8091\r\n    enable-degrade: false\r\n    disable-global-transaction: ${seata.service.enable-degrade}\r\n  config:\r\n    type: nacos\r\n    nacos:\r\n      serverAddr: nacos:8848\r\n      namespace: seata\r\n      group: SEATA_GROUP\r\n  registry:\r\n    type: ${seata.config.type}\r\n    nacos:\r\n      server-addr: ${seata.config.nacos.serverAddr}\r\n      namespace: ${seata.config.nacos.namespace}\r\n      application: seata-server    ', '58d2d230e0658197230af045a850a4d3', '2021-01-21 08:13:30', '2021-01-21 08:13:30', NULL, '58.212.133.156', '', 'test', NULL, NULL, NULL, 'yaml', NULL);

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint UNSIGNED NOT NULL,
  `nid` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 360 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (79, 313, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: user-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  ', '60458cede6ddd9629e10d38192a56f5b', '2010-05-05 00:00:00', '2021-02-01 08:18:46', NULL, '58.212.133.192', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 314, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: user-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/user/sentinel_test/*\'\n      - \'/auth/user/login_info\'', '79e53be71d3d46d8531d84aa04fca366', '2010-05-05 00:00:00', '2021-02-01 08:22:27', NULL, '58.212.133.192', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 315, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: user-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/user/sentinel_test/*\'', 'b007d177281fb33c0ecc7c8265ec9810', '2010-05-05 00:00:00', '2021-02-01 08:25:28', NULL, '58.212.133.192', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 316, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: user-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/user/sentinel_test/*\'\n      - \'/auth/user/login_info\'', '79e53be71d3d46d8531d84aa04fca366', '2010-05-05 00:00:00', '2021-02-01 08:33:17', NULL, '58.212.133.192', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 317, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: user-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/user/sentinel_test/*\'', 'b007d177281fb33c0ecc7c8265ec9810', '2010-05-05 00:00:00', '2021-02-03 07:59:43', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 318, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: user-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  ', '60458cede6ddd9629e10d38192a56f5b', '2010-05-05 00:00:00', '2021-02-03 08:00:19', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 319, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/city/*Mapper.xml\n    - classpath*:/mapper/country/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.auth.feign: debug\n    com.sh.order.feign: debug\n    com.sh.organization.notable.mapper: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', '296181aceac09318e6f6789f2c7f8e53', '2010-05-05 00:00:00', '2021-02-03 10:38:30', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 320, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/city/*Mapper.xml\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.auth.feign: debug\n    com.sh.order.feign: debug\n    com.sh.organization.notable.mapper: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', '65922ae2f79749ee4e3b2d5e61c228d7', '2010-05-05 00:00:00', '2021-02-03 11:42:17', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 321, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/city/*Mapper.xml\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.auth.feign: debug\n    com.sh.order.feign: debug\n    com.sh.organization.notable.mapper: debug\n    com.sh.organization.resource.mapper: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', '9496c79574515cdb44ac2c9b1fc98333', '2010-05-05 00:00:00', '2021-02-03 12:31:34', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 322, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.auth.feign: debug\n    com.sh.order.feign: debug\n    com.sh.organization.notable.mapper: debug\n    com.sh.organization.resource.mapper: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', 'c24884b67de2c9fed51721c3a20a2cfd', '2010-05-05 00:00:00', '2021-02-03 12:38:02', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (48, 323, 'auth-test.yml', 'TEST_GROUP', '', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8858\n        port: 8719\n      datasource:\n        one:\n          nacos:\n            server-addr: nacos:8848\n            dataId: auth\n            namespace: persistence\n            groupId: PERSISTENCE_GROUP\n            data-type: json\n            rule-type: flow            \n  redis:\n    host: redis\n    password: 123456        \n\n', 'f21a600ae35dd13e26adb66b4d6a939d', '2010-05-05 00:00:00', '2021-02-03 14:48:38', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 324, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n  redis:\n    host: redis\n    password: 123456\nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  ', '722a80bcd77b79ea8c8d2af49f391127', '2010-05-05 00:00:00', '2021-02-03 14:48:58', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 325, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  ', '494a1ac672f9435ec27a3585b3e32559', '2010-05-05 00:00:00', '2021-02-03 14:49:04', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (48, 326, 'auth-test.yml', 'TEST_GROUP', '', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8858\n        port: 8719\n      datasource:\n        one:\n          nacos:\n            server-addr: nacos:8848\n            dataId: auth\n            namespace: persistence\n            groupId: PERSISTENCE_GROUP\n            data-type: json\n            rule-type: flow            \n   \n\n', '250e8a7d60301a72d6698d8492b71177', '2010-05-05 00:00:00', '2021-02-04 05:46:45', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 327, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  ', '494a1ac672f9435ec27a3585b3e32559', '2010-05-05 00:00:00', '2021-02-05 08:38:46', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 328, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - /auth/oauth/sentinel_test/*', '163862d7896f1309522867092106d6c6', '2010-05-05 00:00:00', '2021-02-05 08:39:11', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 329, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - /auth/oauth/sentinel_test/*', '163862d7896f1309522867092106d6c6', '2010-05-05 00:00:00', '2021-02-05 08:39:20', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 330, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - /auth/oauth/sentinel_test/*', '163862d7896f1309522867092106d6c6', '2010-05-05 00:00:00', '2021-02-05 08:43:09', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 331, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/**\'', '29f52113821c58c00b99137c15f358ab', '2010-05-05 00:00:00', '2021-02-05 08:47:02', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 332, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test\'', '3bde6006237e7d734cbe9f13aae1591c', '2010-05-05 00:00:00', '2021-02-05 08:48:27', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 333, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'', '206553afe3a7e2e486021768d53d3b6f', '2010-05-05 00:00:00', '2021-02-05 08:50:13', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 334, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test\'', '3bde6006237e7d734cbe9f13aae1591c', '2010-05-05 00:00:00', '2021-02-05 08:56:34', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 335, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    - classpath*:/mapper/menu/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.auth.feign: debug\n    com.sh.order.feign: debug\n    com.sh.organization.notable.mapper: debug\n    com.sh.organization.resource.mapper: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', '1afd01942ae43062177f22474e03f08f', '2010-05-05 00:00:00', '2021-02-05 14:29:47', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 336, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'', '206553afe3a7e2e486021768d53d3b6f', '2010-05-05 00:00:00', '2021-02-06 06:00:13', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 337, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    - classpath*:/mapper/menu/*Mapper.xml\n    - classpath*:/mapper/resource/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.auth.feign: debug\n    com.sh.order.feign: debug\n    com.sh.organization.notable.mapper: debug\n    com.sh.organization.resource.mapper: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', '49f0b4e0bf003eef00a9260e63f39561', '2010-05-05 00:00:00', '2021-02-06 07:19:38', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 338, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'', '547479e42dad16701dbf3c7fc21b7667', '2010-05-05 00:00:00', '2021-02-06 07:33:44', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 339, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/user/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'', '206553afe3a7e2e486021768d53d3b6f', '2010-05-05 00:00:00', '2021-02-06 07:40:55', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (2, 340, 'common-test.yml', 'SHARED_GROUP', '', 'mybatis-plus:\n  global-config:\n    db-config:\n      logic-delete-field: del_flag\n      logic-delete-value: 1\n      logic-not-delete-value: 0\n  mapper-locations:\n    - classpath*:/mapper/country/*Mapper.xml\n    - classpath*:/mapper/user/*Mapper.xml\n    - classpath*:/mapper/role/*Mapper.xml\n    - classpath*:/mapper/menu/*Mapper.xml\n    - classpath*:/mapper/resource/*Mapper.xml\n    \n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    com.sh.organization.user.mapper: debug\n    com.sh.organization.menu.mapper: debug\n    com.sh.organization.role.mapper: debug\n    com.sh.organization.rolemenu.mapper: debug\n    com.sh.organization.resource.mapper: debug\n    com.sh.organization.city.mapper: debug\n    com.sh.organization.country.mapper: debug\n    com.sh.organization.tms.mapper: debug\n    com.sh.organization.notable.mapper: debug\n    com.sh.storage.mapper: debug\n    com.sh.account.mapper: debug\n    com.sh.order.mapper: debug\n    com.sh.order.feign: debug\n    com.sh.auth.feign.service: debug\n    com.sh.gateway.feign.service: debug\n    \njasypt:\n  encryptor:\n    password: jasyptTest\n\nfeign:\n  sentinel:\n    enabled: true\n\nribbon:\n  ReadTimeout: 3000\n  ConnectTimeout: ${ribbon.ReadTimeout}\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'  ', '090e95de82435e95b933db2319537e33', '2010-05-05 00:00:00', '2021-02-06 07:41:10', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 341, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'', '547479e42dad16701dbf3c7fc21b7667', '2010-05-05 00:00:00', '2021-02-06 15:15:52', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (48, 342, 'auth-test.yml', 'TEST_GROUP', '', 'spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n    username: sh\n    password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8858\n        port: 8719\n      datasource:\n        one:\n          nacos:\n            server-addr: nacos:8848\n            dataId: auth\n            namespace: persistence\n            groupId: PERSISTENCE_GROUP\n            data-type: json\n            rule-type: flow            \n   \n\n', '250e8a7d60301a72d6698d8492b71177', '2010-05-05 00:00:00', '2021-02-07 08:18:16', NULL, '180.111.133.63', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 343, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'', '547479e42dad16701dbf3c7fc21b7667', '2010-05-05 00:00:00', '2021-02-19 10:30:53', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (61, 344, 'organization-test.yml', 'TEST_GROUP', '', 'spring:\n  autoconfigure:\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    dynamic:\n      primary: master\n      strict: false\n      datasource:\n        master:\n          url: jdbc:mysql://mysql:3306/test_library?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true\n          username: sh\n          password: ENC(HtPI6aowIQt10BX0NoqTjf62LvZzX/d7YN4F0hrzVMw/so0bCJz111wKbmXLHHao)\n          driver-class-name: com.mysql.cj.jdbc.Driver\n        sqlserver:\n          url: jdbc:sqlserver://10.250.60.63:1433;DatabaseName=im\n          username: sa\n          password: sqlserver2012\n          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver\n  redis:\n    host: redis\n    password: 123456\n\nminio:\n  endpoint: http://minio:9000\n  access-key: minio\n  secret-key: minio123456\n  bucket-name: head   \n\n', '68871bca99c496b026acf0eb0211dc53', '2010-05-05 00:00:00', '2021-02-19 10:56:25', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 345, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'  \n      - \'/auth/oauth/sentinel_test/*\'\n\n  redis:\n    host: redis\n    password: 123456      ', '840f3e0489e5e9e2b8389a62fa0423da', '2010-05-05 00:00:00', '2021-02-19 10:57:19', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 346, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', '09aa6f13dd6b9d3a097851c97cbd962e', '2010-05-05 00:00:00', '2021-02-19 10:57:49', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 347, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', '09aa6f13dd6b9d3a097851c97cbd962e', '2010-05-05 00:00:00', '2021-02-28 11:03:20', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 348, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/test/token\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', 'da47915ae0c690ec24da7c053b97a04f', '2010-05-05 00:00:00', '2021-02-28 11:03:36', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 349, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/test/token\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', '72b9e8628fb53938600a3cab250b247d', '2010-05-05 00:00:00', '2021-02-28 11:04:15', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 350, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/test/token/*\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', '47e8edf28c355c07322b49ee33e83d82', '2010-05-05 00:00:00', '2021-02-28 11:06:16', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 351, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/pauth/token/**\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', '328833a55a19179c0432fbc4b7dc3724', '2010-05-05 00:00:00', '2021-02-28 11:09:50', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 352, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token/**\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', 'f232a1d6626d7ee874168476c93c9305', '2010-05-05 00:00:00', '2021-02-28 11:13:27', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 353, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token/**\'\n      - \'/auth/oauth/sentinel_test/*\'\n\n', 'f232a1d6626d7ee874168476c93c9305', '2010-05-05 00:00:00', '2021-02-28 11:17:59', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 354, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/oauth/sentinel_test\'\n\n', 'f56ddea1377913e063f660b2de4b26a5', '2010-05-05 00:00:00', '2021-02-28 11:45:08', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 355, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/oauth/sentinel_test\'\n\n', 'f56ddea1377913e063f660b2de4b26a5', '2010-05-05 00:00:00', '2021-02-28 11:51:24', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 356, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/sentinel/test\'\n\n', '7d534db1d30ad1c76c67c94a42f6aa59', '2010-05-05 00:00:00', '2021-02-28 11:52:39', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 357, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/auth/token\'\n      - \'/auth/sentinel/test\'\n\n', '8a50893b53d7e38a4701ac018c9763ec', '2010-05-05 00:00:00', '2021-02-28 12:07:21', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 358, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/rsa/public_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/sentinel/test\'\n\n', '7d534db1d30ad1c76c67c94a42f6aa59', '2010-05-05 00:00:00', '2021-02-28 12:16:33', NULL, '49.74.67.42', 'U', 'test');
INSERT INTO `his_config_info` VALUES (79, 359, 'gateway-test.yml', 'TEST_GROUP', '', 'spring:\n  cloud:\n    gateway:\n      routes:\n        - id: auth-route\n          uri: http://localhost:3020\n          predicates:\n            - Path=/auth/**\n          filters:\n            - StripPrefix=1\n\n        - id: organization-route\n          uri: http://localhost:2097\n          predicates:\n            - Path=/organization/**\n          filters:\n            - StripPrefix=1\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          jwk-set-uri: \'http://localhost:3020/oauth/rsa_key\'\n          \n  redis:\n    host: redis\n    password: 123456\n    \nsecure:\n  ignore:\n    urls:\n      - \'/actuator/**\'\n      - \'/auth/oauth/token\'\n      - \'/auth/sentinel/test\'\n\n', 'e384e5891637fe3b04d56e20c65514fa', '2010-05-05 00:00:00', '2021-02-28 12:17:37', NULL, '49.74.67.42', 'U', 'test');

-- ----------------------------
-- Table structure for oauth_client_details
-- ----------------------------
DROP TABLE IF EXISTS `oauth_client_details`;
CREATE TABLE `oauth_client_details`  (
  `client_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '客户端id',
  `resource_ids` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '资源列表',
  `client_secret` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '客户端密钥',
  `scope` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '权限范围',
  `authorized_grant_types` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '授权类型',
  `web_server_redirect_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '回调地址',
  `authorities` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '角色',
  `access_token_validity` int NULL DEFAULT NULL COMMENT '令牌有效期',
  `refresh_token_validity` int NULL DEFAULT NULL COMMENT '刷新令牌有效期',
  `additional_information` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '预留字段',
  `archived` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '扩展字段',
  `autoapprove` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否信任客户端，只适用于grant_type=\"authorization_code\"（true信任 false 不信任，默认false）'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '认证授权客户端表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of oauth_client_details
-- ----------------------------
INSERT INTO `oauth_client_details` VALUES ('sh', '', '$2a$10$4VpmouvhmtVpP8bd7t9f7e6dC1PU2xNycSEeCyGag53TJm3PxmpuO', 'read,write,trust,all', 'authorization_code,password,client_credentials,implicit,refresh_token', '', '', 7200, 259200, NULL, NULL, 'true');

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO `tenant_info` VALUES (1, '1', 'test', 'test', '测试环境配置', 'nacos', 1609679137369, 1609679137369);
INSERT INTO `tenant_info` VALUES (2, '1', 'persistence', 'persistence', 'sentinel控制台持久化配置', 'nacos', 1609679804408, 1609683560536);
INSERT INTO `tenant_info` VALUES (3, '1', 'seata', 'seata', 'seata配置', 'nacos', 1609684319622, 1609684319622);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);
INSERT INTO `users` VALUES ('nacosadminguest', '$2a$10$5jQPRFZczvz5mvDiCHIVXukhSm/ZAH/GvBEVu0JS1CjNnUVrZRJeC', 1);

SET FOREIGN_KEY_CHECKS = 1;
